name = "Monodromy"
uuid = "c42699b3-6a89-4f27-9b41-93396bab36cf"
version = "0.1.0"
authors = ["Ophelia Adams"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.3"
GLMakie = "0.13.6"
Observables = "0.5.5"
Printf = "1.11.0"
Test = "1.11.0"
