name = "Monodromy"
uuid = "c42699b3-6a89-4f27-9b41-93396bab36cf"
version = "0.1.0"
authors = ["Ophelia Adams"]

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
GLMakie = "0.13.6"
Test = "1.11.0"
julia = "1.12.2"
